name: Fetch Google Trends

on:
  schedule:
  - cron: "0 23 * * *"  # 北京时间每天早上7点 23:00 UTC 自动运行
  workflow_dispatch:      # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python fetch_trends.py
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/trends.csv
          git commit -m "update trends" || echo "no changes"
          git push
